-- ==============================================================================
-- BSC TEXTILES HRMS - CONSOLIDATED MySQL 8.0 SCHEMA (Prisma-canonical DDL)
-- Generated from validated schema state. Equivalent to migrations 001-010.
-- ==============================================================================

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `user` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `passwordHash` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fullName` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` enum('SUPER_ADMIN','ADMIN','HR_MANAGER','HR_EXECUTIVE','PAYROLL_MANAGER','LOCATION_MANAGER','FLOOR_MANAGER','DEPARTMENT_MANAGER','TEAM_LEAD','SALES_EMPLOYEE','TEA_BREAK_MANAGER','T_SHOP_OWNER','HR_AUDITOR','EMPLOYEE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'EMPLOYEE',
  `permissions` json DEFAULT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT '1',
  `lastLoginAt` datetime(3) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `User_email_key` (`email`),
  KEY `User_email_idx` (`email`),
  KEY `User_role_idx` (`role`),
  KEY `User_locationId_idx` (`locationId`),
  KEY `User_employeeId_fkey` (`employeeId`),
  CONSTRAINT `User_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `User_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `location` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `address` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pin` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `whatsapp` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `managerId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hrManagerId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `openingTime` datetime(3) DEFAULT NULL,
  `closingTime` datetime(3) DEFAULT NULL,
  `status` enum('ACTIVE','INACTIVE','ARCHIVED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Location_code_key` (`code`),
  KEY `Location_code_idx` (`code`),
  KEY `Location_status_idx` (`status`),
  KEY `Location_managerId_fkey` (`managerId`),
  KEY `Location_hrManagerId_fkey` (`hrManagerId`),
  CONSTRAINT `Location_hrManagerId_fkey` FOREIGN KEY (`hrManagerId`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Location_managerId_fkey` FOREIGN KEY (`managerId`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `floor` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floorNumber` int NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floorManagerId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `assistantManagerId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('ACTIVE','INACTIVE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Floor_locationId_floorNumber_key` (`locationId`,`floorNumber`),
  KEY `Floor_locationId_idx` (`locationId`),
  KEY `Floor_floorManagerId_idx` (`floorManagerId`),
  KEY `Floor_assistantManagerId_fkey` (`assistantManagerId`),
  CONSTRAINT `Floor_assistantManagerId_fkey` FOREIGN KEY (`assistantManagerId`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Floor_floorManagerId_fkey` FOREIGN KEY (`floorManagerId`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Floor_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `department` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floorId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `managerId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Department_locationId_code_key` (`locationId`,`code`),
  KEY `Department_locationId_idx` (`locationId`),
  KEY `Department_floorId_idx` (`floorId`),
  KEY `Department_managerId_fkey` (`managerId`),
  CONSTRAINT `Department_floorId_fkey` FOREIGN KEY (`floorId`) REFERENCES `floor` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Department_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Department_managerId_fkey` FOREIGN KEY (`managerId`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `section` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floorId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `supervisorId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Section_locationId_code_key` (`locationId`,`code`),
  KEY `Section_locationId_idx` (`locationId`),
  KEY `Section_floorId_idx` (`floorId`),
  KEY `Section_departmentId_idx` (`departmentId`),
  KEY `Section_supervisorId_fkey` (`supervisorId`),
  CONSTRAINT `Section_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Section_floorId_fkey` FOREIGN KEY (`floorId`) REFERENCES `floor` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Section_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Section_supervisorId_fkey` FOREIGN KEY (`supervisorId`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sellingpoint` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floorId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sectionId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `managerId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `targetAmount` decimal(15,2) DEFAULT NULL,
  `incentiveRuleId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `performanceScore` decimal(5,2) DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `SellingPoint_locationId_code_key` (`locationId`,`code`),
  KEY `SellingPoint_locationId_idx` (`locationId`),
  KEY `SellingPoint_floorId_idx` (`floorId`),
  KEY `SellingPoint_sectionId_idx` (`sectionId`),
  KEY `SellingPoint_departmentId_fkey` (`departmentId`),
  KEY `SellingPoint_managerId_fkey` (`managerId`),
  KEY `SellingPoint_incentiveRuleId_fkey` (`incentiveRuleId`),
  CONSTRAINT `SellingPoint_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `SellingPoint_floorId_fkey` FOREIGN KEY (`floorId`) REFERENCES `floor` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `SellingPoint_incentiveRuleId_fkey` FOREIGN KEY (`incentiveRuleId`) REFERENCES `incentiverule` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `SellingPoint_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `SellingPoint_managerId_fkey` FOREIGN KEY (`managerId`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `SellingPoint_sectionId_fkey` FOREIGN KEY (`sectionId`) REFERENCES `section` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `employeesellingpoint` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sellingPointId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `assignedDate` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `isPrimary` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `EmployeeSellingPoint_employeeId_sellingPointId_key` (`employeeId`,`sellingPointId`),
  KEY `EmployeeSellingPoint_employeeId_idx` (`employeeId`),
  KEY `EmployeeSellingPoint_sellingPointId_idx` (`sellingPointId`),
  CONSTRAINT `EmployeeSellingPoint_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `EmployeeSellingPoint_sellingPointId_fkey` FOREIGN KEY (`sellingPointId`) REFERENCES `sellingpoint` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `employee` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeCode` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `firstName` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lastName` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fullName` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gender` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dateOfBirth` datetime(3) DEFAULT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floorId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sectionId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shiftId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `designation` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role` enum('SUPER_ADMIN','ADMIN','HR_MANAGER','HR_EXECUTIVE','PAYROLL_MANAGER','LOCATION_MANAGER','FLOOR_MANAGER','DEPARTMENT_MANAGER','TEAM_LEAD','SALES_EMPLOYEE','TEA_BREAK_MANAGER','T_SHOP_OWNER','HR_AUDITOR','EMPLOYEE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'EMPLOYEE',
  `status` enum('ACTIVE','INACTIVE','ON_LEAVE','TERMINATED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  `joiningDate` datetime(3) NOT NULL,
  `exitDate` datetime(3) DEFAULT NULL,
  `faceProfileId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qrCodeId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dailyQRCodeId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Employee_employeeCode_key` (`employeeCode`),
  UNIQUE KEY `Employee_email_key` (`email`),
  KEY `Employee_employeeCode_idx` (`employeeCode`),
  KEY `Employee_locationId_idx` (`locationId`),
  KEY `Employee_floorId_idx` (`floorId`),
  KEY `Employee_departmentId_idx` (`departmentId`),
  KEY `Employee_sectionId_idx` (`sectionId`),
  KEY `Employee_status_idx` (`status`),
  KEY `Employee_shiftId_fkey` (`shiftId`),
  KEY `Employee_faceProfileId_fkey` (`faceProfileId`),
  KEY `Employee_qrCodeId_fkey` (`qrCodeId`),
  KEY `Employee_dailyQRCodeId_fkey` (`dailyQRCodeId`),
  CONSTRAINT `Employee_dailyQRCodeId_fkey` FOREIGN KEY (`dailyQRCodeId`) REFERENCES `qrcode` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Employee_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Employee_faceProfileId_fkey` FOREIGN KEY (`faceProfileId`) REFERENCES `faceprofile` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Employee_floorId_fkey` FOREIGN KEY (`floorId`) REFERENCES `floor` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Employee_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Employee_qrCodeId_fkey` FOREIGN KEY (`qrCodeId`) REFERENCES `qrcode` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Employee_sectionId_fkey` FOREIGN KEY (`sectionId`) REFERENCES `section` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Employee_shiftId_fkey` FOREIGN KEY (`shiftId`) REFERENCES `shift` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `shift` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `startTime` datetime(3) NOT NULL,
  `endTime` datetime(3) NOT NULL,
  `gracePeriod` int NOT NULL DEFAULT '5',
  `lateThreshold` int NOT NULL DEFAULT '5',
  `earlyLoginIncentive` tinyint(1) NOT NULL DEFAULT '1',
  `earlyLoginRatePerSecond` decimal(10,4) NOT NULL DEFAULT '1.0000',
  `maxDailyEarlyIncentive` decimal(15,2) DEFAULT NULL,
  `maxMonthlyEarlyIncentive` decimal(15,2) DEFAULT NULL,
  `latePenaltyEnabled` tinyint(1) NOT NULL DEFAULT '0',
  `latePenaltyRatePerSecond` decimal(10,4) NOT NULL DEFAULT '1.0000',
  `maxDailyLatePenalty` decimal(15,2) DEFAULT NULL,
  `maxMonthlyLatePenalty` decimal(15,2) DEFAULT NULL,
  `overtimeEnabled` tinyint(1) NOT NULL DEFAULT '1',
  `overtimeRatePerSecond` decimal(10,4) DEFAULT NULL,
  `earlyLogoutPenaltyEnabled` tinyint(1) NOT NULL DEFAULT '0',
  `earlyLogoutRatePerSecond` decimal(10,4) DEFAULT NULL,
  `lunchDurationMinutes` int NOT NULL DEFAULT '100',
  `teaDurationMinutes` int NOT NULL DEFAULT '20',
  `maleLunchMinutes` int NOT NULL DEFAULT '100',
  `femaleLunchMinutes` int NOT NULL DEFAULT '40',
  `maleTeaMinutes` int NOT NULL DEFAULT '20',
  `femaleTeaMinutes` int NOT NULL DEFAULT '15',
  `faceVerificationThreshold` decimal(5,2) NOT NULL DEFAULT '85.00',
  `qrDailyTokenEnabled` tinyint(1) NOT NULL DEFAULT '1',
  `qrOneTimeScan` tinyint(1) NOT NULL DEFAULT '1',
  `scannerRoles` json DEFAULT NULL,
  `status` enum('ACTIVE','INACTIVE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Shift_locationId_code_key` (`locationId`,`code`),
  KEY `Shift_locationId_idx` (`locationId`),
  KEY `Shift_status_idx` (`status`),
  KEY `Shift_departmentId_fkey` (`departmentId`),
  CONSTRAINT `Shift_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Shift_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `attendancerules` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `loginTime` datetime(3) NOT NULL,
  `logoutTime` datetime(3) NOT NULL,
  `gracePeriodMinutes` int NOT NULL DEFAULT '5',
  `lateThresholdMinutes` int NOT NULL DEFAULT '5',
  `earlyLoginIncentiveEnabled` tinyint(1) NOT NULL DEFAULT '1',
  `earlyLoginRatePerSecond` decimal(10,4) NOT NULL DEFAULT '1.0000',
  `earlyLoginMaxDaily` decimal(15,2) DEFAULT NULL,
  `earlyLoginMaxMonthly` decimal(15,2) DEFAULT NULL,
  `latePenaltyEnabled` tinyint(1) NOT NULL DEFAULT '0',
  `latePenaltyRatePerSecond` decimal(10,4) NOT NULL DEFAULT '1.0000',
  `latePenaltyMaxDaily` decimal(15,2) DEFAULT NULL,
  `latePenaltyMaxMonthly` decimal(15,2) DEFAULT NULL,
  `overtimeIncentiveEnabled` tinyint(1) NOT NULL DEFAULT '0',
  `overtimeRatePerSecond` decimal(10,4) DEFAULT NULL,
  `earlyLogoutPenaltyEnabled` tinyint(1) NOT NULL DEFAULT '0',
  `earlyLogoutRatePerSecond` decimal(10,4) DEFAULT NULL,
  `lunchDurationMinutes` int NOT NULL DEFAULT '100',
  `teaDurationMinutes` int NOT NULL DEFAULT '20',
  `maleLunchMinutes` int NOT NULL DEFAULT '100',
  `femaleLunchMinutes` int NOT NULL DEFAULT '40',
  `maleTeaMinutes` int NOT NULL DEFAULT '20',
  `femaleTeaMinutes` int NOT NULL DEFAULT '15',
  `faceVerificationThreshold` decimal(5,2) NOT NULL DEFAULT '85.00',
  `qrDailyTokenEnabled` tinyint(1) NOT NULL DEFAULT '1',
  `qrOneTimeScan` tinyint(1) NOT NULL DEFAULT '1',
  `scannerRoles` json DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `AttendanceRules_locationId_key` (`locationId`),
  KEY `AttendanceRules_locationId_idx` (`locationId`),
  CONSTRAINT `AttendanceRules_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `breakrule` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `floorId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shiftId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employeeGroup` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `breakType` enum('LUNCH','TEA','OTHER') COLLATE utf8mb4_unicode_ci NOT NULL,
  `durationMinutes` int NOT NULL,
  `maxOccurrences` int NOT NULL DEFAULT '1',
  `isPaid` tinyint(1) NOT NULL DEFAULT '1',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `BreakRule_locationId_idx` (`locationId`),
  KEY `BreakRule_departmentId_idx` (`departmentId`),
  KEY `BreakRule_floorId_idx` (`floorId`),
  KEY `BreakRule_shiftId_idx` (`shiftId`),
  CONSTRAINT `BreakRule_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `BreakRule_floorId_fkey` FOREIGN KEY (`floorId`) REFERENCES `floor` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `BreakRule_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `BreakRule_shiftId_fkey` FOREIGN KEY (`shiftId`) REFERENCES `shift` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `employeebreak` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `breakType` enum('LUNCH','TEA','OTHER') COLLATE utf8mb4_unicode_ci NOT NULL,
  `breakDate` date NOT NULL,
  `startTime` datetime(3) DEFAULT NULL,
  `endTime` datetime(3) DEFAULT NULL,
  `allowedDuration` int NOT NULL,
  `actualDuration` int DEFAULT NULL,
  `excessDuration` int DEFAULT NULL,
  `status` enum('NOT_STARTED','ACTIVE','COMPLETED','EXCEEDED','MANUALLY_ADJUSTED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NOT_STARTED',
  `qrScanId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `EmployeeBreak_employeeId_breakDate_idx` (`employeeId`,`breakDate`),
  KEY `EmployeeBreak_breakType_idx` (`breakType`),
  KEY `EmployeeBreak_status_idx` (`status`),
  KEY `EmployeeBreak_qrScanId_fkey` (`qrScanId`),
  CONSTRAINT `EmployeeBreak_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `EmployeeBreak_qrScanId_fkey` FOREIGN KEY (`qrScanId`) REFERENCES `qrscanrecord` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `weeklyoffrule` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floorId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shiftId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dayOfWeek` enum('SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','ROTATIONAL') COLLATE utf8mb4_unicode_ci NOT NULL,
  `isRotational` tinyint(1) NOT NULL DEFAULT '0',
  `rotationPattern` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `effectiveFrom` date NOT NULL,
  `effectiveTo` date DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `WeeklyOffRule_locationId_idx` (`locationId`),
  KEY `WeeklyOffRule_employeeId_idx` (`employeeId`),
  KEY `WeeklyOffRule_floorId_idx` (`floorId`),
  KEY `WeeklyOffRule_departmentId_idx` (`departmentId`),
  KEY `WeeklyOffRule_shiftId_idx` (`shiftId`),
  CONSTRAINT `WeeklyOffRule_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `WeeklyOffRule_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `WeeklyOffRule_floorId_fkey` FOREIGN KEY (`floorId`) REFERENCES `floor` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `WeeklyOffRule_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `WeeklyOffRule_shiftId_fkey` FOREIGN KEY (`shiftId`) REFERENCES `shift` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `holiday` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `date` date NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isRecurring` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `Holiday_date_idx` (`date`),
  KEY `Holiday_locationId_idx` (`locationId`),
  KEY `Holiday_departmentId_fkey` (`departmentId`),
  CONSTRAINT `Holiday_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Holiday_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `faceprofile` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `faceData` longblob NOT NULL,
  `enrolledAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `FaceProfile_employeeId_key` (`employeeId`),
  CONSTRAINT `FaceProfile_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `faceverification` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `deviceId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `verifiedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `matchPercentage` decimal(5,2) NOT NULL,
  `threshold` decimal(5,2) NOT NULL,
  `result` enum('VERIFIED','FAILED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `purpose` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT 'attendance',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `FaceVerification_employeeId_idx` (`employeeId`),
  KEY `FaceVerification_locationId_idx` (`locationId`),
  KEY `FaceVerification_verifiedAt_idx` (`verifiedAt`),
  KEY `FaceVerification_result_idx` (`result`),
  CONSTRAINT `FaceVerification_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FaceVerification_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `qrcode` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` enum('EMPLOYEE','DAILY') COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `validFrom` datetime(3) NOT NULL,
  `validTo` datetime(3) NOT NULL,
  `isConsumed` tinyint(1) NOT NULL DEFAULT '0',
  `consumedAt` datetime(3) DEFAULT NULL,
  `consumedBy` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `purpose` enum('ATTENDANCE_CHECK_IN','ATTENDANCE_CHECK_OUT','LUNCH_START','LUNCH_END','TEA_BREAK_START','TEA_BREAK_END','BREAK_START','BREAK_END','SELLING_POINT_CHECK_IN') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `QRCode_token_key` (`token`),
  KEY `QRCode_employeeId_idx` (`employeeId`),
  KEY `QRCode_token_idx` (`token`),
  KEY `QRCode_validFrom_validTo_idx` (`validFrom`,`validTo`),
  KEY `QRCode_isConsumed_idx` (`isConsumed`),
  KEY `QRCode_locationId_fkey` (`locationId`),
  CONSTRAINT `QRCode_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `QRCode_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `qrscanrecord` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `qrCodeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `scannerId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sellingPointId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `purpose` enum('ATTENDANCE_CHECK_IN','ATTENDANCE_CHECK_OUT','LUNCH_START','LUNCH_END','TEA_BREAK_START','TEA_BREAK_END','BREAK_START','BREAK_END','SELLING_POINT_CHECK_IN') COLLATE utf8mb4_unicode_ci NOT NULL,
  `result` enum('SUCCESS','ALREADY_SCANNED','EXPIRED','UNAUTHORIZED_SCANNER','LOCATION_MISMATCH','INVALID_TOKEN','EMPLOYEE_INACTIVE','REVOKED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `failureReason` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scannedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `deviceInfo` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ipAddress` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `QRScanRecord_employeeId_scannedAt_idx` (`employeeId`,`scannedAt`),
  KEY `QRScanRecord_scannerId_scannedAt_idx` (`scannerId`,`scannedAt`),
  KEY `QRScanRecord_locationId_scannedAt_idx` (`locationId`,`scannedAt`),
  KEY `QRScanRecord_result_idx` (`result`),
  KEY `QRScanRecord_qrCodeId_fkey` (`qrCodeId`),
  KEY `QRScanRecord_sellingPointId_fkey` (`sellingPointId`),
  CONSTRAINT `QRScanRecord_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `QRScanRecord_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `QRScanRecord_qrCodeId_fkey` FOREIGN KEY (`qrCodeId`) REFERENCES `qrcode` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `QRScanRecord_scannerId_fkey` FOREIGN KEY (`scannerId`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `QRScanRecord_sellingPointId_fkey` FOREIGN KEY (`sellingPointId`) REFERENCES `sellingpoint` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `incentiverule` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `incentiveType` enum('INDIVIDUAL','DEPARTMENT','LOCATION','FLOOR','SELLING_POINT','SALES','ATTENDANCE','PERFORMANCE','EARLY_LOGIN','TARGET','CUSTOM') COLLATE utf8mb4_unicode_ci NOT NULL,
  `calculationType` enum('FIXED_AMOUNT','PER_HOUR','PER_MINUTE','PER_SECOND','PERCENTAGE','TARGET_BASED','PERFORMANCE_BASED','ATTENDANCE_BASED','CUSTOM_RULE') COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `floorId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sellingPointId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(15,2) DEFAULT NULL,
  `percentage` decimal(5,2) DEFAULT NULL,
  `targetAmount` decimal(15,2) DEFAULT NULL,
  `effectiveFrom` date NOT NULL,
  `effectiveTo` date DEFAULT NULL,
  `maxDailyAmount` decimal(15,2) DEFAULT NULL,
  `maxMonthlyAmount` decimal(15,2) DEFAULT NULL,
  `status` enum('ACTIVE','INACTIVE','PENDING_APPROVAL','APPROVED','REJECTED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  `createdById` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `approvedById` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `approvedAt` datetime(3) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `IncentiveRule_locationId_idx` (`locationId`),
  KEY `IncentiveRule_departmentId_idx` (`departmentId`),
  KEY `IncentiveRule_floorId_idx` (`floorId`),
  KEY `IncentiveRule_sellingPointId_idx` (`sellingPointId`),
  KEY `IncentiveRule_employeeId_idx` (`employeeId`),
  KEY `IncentiveRule_status_idx` (`status`),
  KEY `IncentiveRule_createdById_fkey` (`createdById`),
  KEY `IncentiveRule_approvedById_fkey` (`approvedById`),
  CONSTRAINT `IncentiveRule_approvedById_fkey` FOREIGN KEY (`approvedById`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `IncentiveRule_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `IncentiveRule_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `IncentiveRule_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `IncentiveRule_floorId_fkey` FOREIGN KEY (`floorId`) REFERENCES `floor` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `IncentiveRule_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `IncentiveRule_sellingPointId_fkey` FOREIGN KEY (`sellingPointId`) REFERENCES `sellingpoint` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `employeeincentive` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `incentiveRuleId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `effectiveFrom` date NOT NULL,
  `effectiveTo` date DEFAULT NULL,
  `status` enum('ACTIVE','INACTIVE','PENDING_APPROVAL','APPROVED','REJECTED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `EmployeeIncentive_employeeId_incentiveRuleId_key` (`employeeId`,`incentiveRuleId`),
  KEY `EmployeeIncentive_employeeId_idx` (`employeeId`),
  KEY `EmployeeIncentive_incentiveRuleId_idx` (`incentiveRuleId`),
  CONSTRAINT `EmployeeIncentive_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `EmployeeIncentive_incentiveRuleId_fkey` FOREIGN KEY (`incentiveRuleId`) REFERENCES `incentiverule` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `incentivetransaction` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `incentiveRuleId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `transactionDate` date NOT NULL,
  `calculationBasis` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `calculatedAmount` decimal(15,2) NOT NULL,
  `calculationDetails` json NOT NULL,
  `status` enum('ACTIVE','INACTIVE','PENDING_APPROVAL','APPROVED','REJECTED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING_APPROVAL',
  `approvedById` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `approvedAt` datetime(3) DEFAULT NULL,
  `payrollRunId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `IncentiveTransaction_employeeId_transactionDate_idx` (`employeeId`,`transactionDate`),
  KEY `IncentiveTransaction_incentiveRuleId_idx` (`incentiveRuleId`),
  KEY `IncentiveTransaction_status_idx` (`status`),
  KEY `IncentiveTransaction_approvedById_fkey` (`approvedById`),
  CONSTRAINT `IncentiveTransaction_approvedById_fkey` FOREIGN KEY (`approvedById`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `IncentiveTransaction_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `IncentiveTransaction_incentiveRuleId_fkey` FOREIGN KEY (`incentiveRuleId`) REFERENCES `incentiverule` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `penaltyrule` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `penaltyType` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `calculationType` enum('FIXED_AMOUNT','PER_HOUR','PER_MINUTE','PER_SECOND','PERCENTAGE','TARGET_BASED','PERFORMANCE_BASED','ATTENDANCE_BASED','CUSTOM_RULE') COLLATE utf8mb4_unicode_ci NOT NULL,
  `amount` decimal(15,2) DEFAULT NULL,
  `percentage` decimal(5,2) DEFAULT NULL,
  `maxDailyAmount` decimal(15,2) DEFAULT NULL,
  `maxMonthlyAmount` decimal(15,2) DEFAULT NULL,
  `effectiveFrom` date NOT NULL,
  `effectiveTo` date DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT '1',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `PenaltyRule_locationId_idx` (`locationId`),
  KEY `PenaltyRule_departmentId_idx` (`departmentId`),
  KEY `PenaltyRule_employeeId_idx` (`employeeId`),
  CONSTRAINT `PenaltyRule_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `PenaltyRule_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `PenaltyRule_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `penaltytransaction` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `penaltyRuleId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `transactionDate` date NOT NULL,
  `calculationBasis` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `calculatedAmount` decimal(15,2) NOT NULL,
  `calculationDetails` json NOT NULL,
  `status` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `approvedById` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `approvedAt` datetime(3) DEFAULT NULL,
  `payrollRunId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `PenaltyTransaction_employeeId_transactionDate_idx` (`employeeId`,`transactionDate`),
  KEY `PenaltyTransaction_penaltyRuleId_idx` (`penaltyRuleId`),
  KEY `PenaltyTransaction_status_idx` (`status`),
  KEY `PenaltyTransaction_approvedById_fkey` (`approvedById`),
  CONSTRAINT `PenaltyTransaction_approvedById_fkey` FOREIGN KEY (`approvedById`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `PenaltyTransaction_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `PenaltyTransaction_penaltyRuleId_fkey` FOREIGN KEY (`penaltyRuleId`) REFERENCES `penaltyrule` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `attendance` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `shiftId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `attendanceDate` date NOT NULL,
  `scheduledLogin` datetime(3) DEFAULT NULL,
  `actualLogin` datetime(3) DEFAULT NULL,
  `scheduledLogout` datetime(3) DEFAULT NULL,
  `actualLogout` datetime(3) DEFAULT NULL,
  `earlyLoginSeconds` int NOT NULL DEFAULT '0',
  `lateLoginSeconds` int NOT NULL DEFAULT '0',
  `earlyLogoutSeconds` int NOT NULL DEFAULT '0',
  `overtimeSeconds` int NOT NULL DEFAULT '0',
  `totalWorkingSeconds` int NOT NULL DEFAULT '0',
  `breakSeconds` int NOT NULL DEFAULT '0',
  `effectiveWorkingSeconds` int NOT NULL DEFAULT '0',
  `earlyLoginIncentive` decimal(15,2) NOT NULL DEFAULT '0.00',
  `lateLoginPenalty` decimal(15,2) NOT NULL DEFAULT '0.00',
  `overtimeIncentive` decimal(15,2) NOT NULL DEFAULT '0.00',
  `earlyLogoutPenalty` decimal(15,2) NOT NULL DEFAULT '0.00',
  `status` enum('PRESENT','ABSENT','LATE','EARLY','ON_LUNCH','ON_TEA_BREAK','ON_OTHER_BREAK','WEEKLY_OFF','OVERTIME','LEFT_STORE','FACE_VERIFIED','FACE_VERIFICATION_FAILED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ABSENT',
  `faceVerified` tinyint(1) NOT NULL DEFAULT '0',
  `faceMatchPercentage` decimal(5,2) DEFAULT NULL,
  `notes` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Attendance_employeeId_attendanceDate_key` (`employeeId`,`attendanceDate`),
  KEY `Attendance_locationId_attendanceDate_idx` (`locationId`,`attendanceDate`),
  KEY `Attendance_shiftId_idx` (`shiftId`),
  KEY `Attendance_status_idx` (`status`),
  CONSTRAINT `Attendance_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Attendance_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Attendance_shiftId_fkey` FOREIGN KEY (`shiftId`) REFERENCES `shift` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `observation` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floorId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sectionId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sellingPointId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `observationType` enum('POSITIVE','IMPROVEMENT','CUSTOMER_SERVICE','SALES','GROOMING','PRODUCT_KNOWLEDGE','ATTENDANCE','DISCIPLINE','SELLING_SKILL','STORE_STANDARD','SAFETY') COLLATE utf8mb4_unicode_ci NOT NULL,
  `level` enum('EXCELLENT','VERY_GOOD','GOOD','NEEDS_IMPROVEMENT','CRITICAL') COLLATE utf8mb4_unicode_ci NOT NULL,
  `score` int NOT NULL,
  `description` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `actionRequired` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `assignedToId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdById` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dueDate` datetime(3) DEFAULT NULL,
  `status` enum('OPEN','IN_PROGRESS','RESOLVED','CLOSED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'OPEN',
  `videoUrl` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `photoUrl` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `Observation_employeeId_idx` (`employeeId`),
  KEY `Observation_locationId_idx` (`locationId`),
  KEY `Observation_status_idx` (`status`),
  KEY `Observation_createdAt_idx` (`createdAt`),
  KEY `Observation_floorId_fkey` (`floorId`),
  KEY `Observation_sectionId_fkey` (`sectionId`),
  KEY `Observation_sellingPointId_fkey` (`sellingPointId`),
  KEY `Observation_assignedToId_fkey` (`assignedToId`),
  KEY `Observation_createdById_fkey` (`createdById`),
  CONSTRAINT `Observation_assignedToId_fkey` FOREIGN KEY (`assignedToId`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Observation_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `Observation_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Observation_floorId_fkey` FOREIGN KEY (`floorId`) REFERENCES `floor` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Observation_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Observation_sectionId_fkey` FOREIGN KEY (`sectionId`) REFERENCES `section` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Observation_sellingPointId_fkey` FOREIGN KEY (`sellingPointId`) REFERENCES `sellingpoint` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `observationreaction` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `observationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `reactionType` enum('ACKNOWLEDGED','COMPLETED','EXCELLENT','REVIEWING','ATTENTION') COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `ObservationReaction_observationId_userId_reactionType_key` (`observationId`,`userId`,`reactionType`),
  KEY `ObservationReaction_observationId_idx` (`observationId`),
  KEY `ObservationReaction_userId_idx` (`userId`),
  CONSTRAINT `ObservationReaction_observationId_fkey` FOREIGN KEY (`observationId`) REFERENCES `observation` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ObservationReaction_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `observationcomment` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `observationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `parentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mentions` json DEFAULT NULL,
  `attachments` json DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ObservationComment_observationId_idx` (`observationId`),
  KEY `ObservationComment_userId_idx` (`userId`),
  KEY `ObservationComment_parentId_idx` (`parentId`),
  CONSTRAINT `ObservationComment_observationId_fkey` FOREIGN KEY (`observationId`) REFERENCES `observation` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ObservationComment_parentId_fkey` FOREIGN KEY (`parentId`) REFERENCES `observationcomment` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ObservationComment_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `observationattachment` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `observationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fileName` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fileUrl` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fileType` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fileSize` int NOT NULL,
  `uploadedById` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `ObservationAttachment_observationId_idx` (`observationId`),
  KEY `ObservationAttachment_uploadedById_fkey` (`uploadedById`),
  CONSTRAINT `ObservationAttachment_observationId_fkey` FOREIGN KEY (`observationId`) REFERENCES `observation` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ObservationAttachment_uploadedById_fkey` FOREIGN KEY (`uploadedById`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `livestream` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floorId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sectionId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sellingPointId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hostId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `streamUrl` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `streamKey` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('SCHEDULED','LIVE','PAUSED','ENDED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'SCHEDULED',
  `viewerCount` int NOT NULL DEFAULT '0',
  `startedAt` datetime(3) DEFAULT NULL,
  `endedAt` datetime(3) DEFAULT NULL,
  `scheduledAt` datetime(3) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `LiveStream_streamKey_key` (`streamKey`),
  KEY `LiveStream_locationId_idx` (`locationId`),
  KEY `LiveStream_status_idx` (`status`),
  KEY `LiveStream_hostId_idx` (`hostId`),
  KEY `LiveStream_floorId_fkey` (`floorId`),
  KEY `LiveStream_sectionId_fkey` (`sectionId`),
  KEY `LiveStream_sellingPointId_fkey` (`sellingPointId`),
  CONSTRAINT `LiveStream_floorId_fkey` FOREIGN KEY (`floorId`) REFERENCES `floor` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `LiveStream_hostId_fkey` FOREIGN KEY (`hostId`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `LiveStream_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `LiveStream_sectionId_fkey` FOREIGN KEY (`sectionId`) REFERENCES `section` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `LiveStream_sellingPointId_fkey` FOREIGN KEY (`sellingPointId`) REFERENCES `sellingpoint` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `livestreamviewer` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `streamId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `joinedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `leftAt` datetime(3) DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `LiveStreamViewer_streamId_userId_key` (`streamId`,`userId`),
  KEY `LiveStreamViewer_streamId_idx` (`streamId`),
  KEY `LiveStreamViewer_userId_idx` (`userId`),
  CONSTRAINT `LiveStreamViewer_streamId_fkey` FOREIGN KEY (`streamId`) REFERENCES `livestream` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `LiveStreamViewer_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `livestreammessage` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `streamId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `LiveStreamMessage_streamId_idx` (`streamId`),
  KEY `LiveStreamMessage_userId_idx` (`userId`),
  CONSTRAINT `LiveStreamMessage_streamId_fkey` FOREIGN KEY (`streamId`) REFERENCES `livestream` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `LiveStreamMessage_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `livestreamreaction` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `streamId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `reactionType` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `LiveStreamReaction_streamId_idx` (`streamId`),
  KEY `LiveStreamReaction_userId_idx` (`userId`),
  CONSTRAINT `LiveStreamReaction_streamId_fkey` FOREIGN KEY (`streamId`) REFERENCES `livestream` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `LiveStreamReaction_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `streamobservation` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `streamId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `observationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `timestampSeconds` int NOT NULL,
  `createdById` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `StreamObservation_streamId_idx` (`streamId`),
  KEY `StreamObservation_observationId_idx` (`observationId`),
  KEY `StreamObservation_createdById_fkey` (`createdById`),
  CONSTRAINT `StreamObservation_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `StreamObservation_observationId_fkey` FOREIGN KEY (`observationId`) REFERENCES `observation` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `StreamObservation_streamId_fkey` FOREIGN KEY (`streamId`) REFERENCES `livestream` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `streamtimestamp` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `streamId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `timestampSeconds` int NOT NULL,
  `label` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `notes` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdById` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `StreamTimestamp_streamId_idx` (`streamId`),
  KEY `StreamTimestamp_createdById_fkey` (`createdById`),
  CONSTRAINT `StreamTimestamp_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `StreamTimestamp_streamId_fkey` FOREIGN KEY (`streamId`) REFERENCES `livestream` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `auditlog` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `action` enum('CREATE','READ','UPDATE','DELETE','LOGIN','LOGOUT','SCAN','VERIFY','APPROVE','REJECT','ASSIGN','CONFIGURE','EXPORT','IMPORT') COLLATE utf8mb4_unicode_ci NOT NULL,
  `entityType` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `entityId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `oldValue` json DEFAULT NULL,
  `newValue` json DEFAULT NULL,
  `ipAddress` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `userAgent` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `AuditLog_userId_idx` (`userId`),
  KEY `AuditLog_locationId_idx` (`locationId`),
  KEY `AuditLog_action_idx` (`action`),
  KEY `AuditLog_entityType_entityId_idx` (`entityType`,`entityId`),
  KEY `AuditLog_createdAt_idx` (`createdAt`),
  CONSTRAINT `AuditLog_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `AuditLog_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `videonote` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `observationId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sellingPointId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `videoUrl` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `thumbnailUrl` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `duration` int DEFAULT NULL,
  `recordedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `VideoNote_employeeId_idx` (`employeeId`),
  KEY `VideoNote_locationId_idx` (`locationId`),
  KEY `VideoNote_observationId_idx` (`observationId`),
  KEY `VideoNote_sellingPointId_fkey` (`sellingPointId`),
  CONSTRAINT `VideoNote_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `VideoNote_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `VideoNote_observationId_fkey` FOREIGN KEY (`observationId`) REFERENCES `observation` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `VideoNote_sellingPointId_fkey` FOREIGN KEY (`sellingPointId`) REFERENCES `sellingpoint` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payrollrun` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `periodStart` date NOT NULL,
  `periodEnd` date NOT NULL,
  `status` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'DRAFT',
  `processedBy` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `processedAt` datetime(3) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payrollitem` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payrollRunId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `basicSalary` decimal(15,2) NOT NULL,
  `earlyIncentive` decimal(15,2) NOT NULL DEFAULT '0.00',
  `attendanceIncentive` decimal(15,2) NOT NULL DEFAULT '0.00',
  `performanceIncentive` decimal(15,2) NOT NULL DEFAULT '0.00',
  `salesIncentive` decimal(15,2) NOT NULL DEFAULT '0.00',
  `overtime` decimal(15,2) NOT NULL DEFAULT '0.00',
  `deductions` decimal(15,2) NOT NULL DEFAULT '0.00',
  `penalties` decimal(15,2) NOT NULL DEFAULT '0.00',
  `netPay` decimal(15,2) NOT NULL,
  `calculationDetails` json NOT NULL,
  `status` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `PayrollItem_payrollRunId_idx` (`payrollRunId`),
  KEY `PayrollItem_employeeId_idx` (`employeeId`),
  CONSTRAINT `PayrollItem_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `PayrollItem_payrollRunId_fkey` FOREIGN KEY (`payrollRunId`) REFERENCES `payrollrun` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `leaverequest` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `leaveType` enum('CASUAL','SICK','EARNED','UNPAID') COLLATE utf8mb4_unicode_ci NOT NULL,
  `startDate` date NOT NULL,
  `endDate` date NOT NULL,
  `days` int NOT NULL,
  `reason` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('PENDING','APPROVED','REJECTED','CANCELLED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `appliedById` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reviewedById` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reviewNote` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `LeaveRequest_locationId_status_idx` (`locationId`,`status`),
  KEY `LeaveRequest_employeeId_idx` (`employeeId`),
  KEY `LeaveRequest_status_createdAt_idx` (`status`,`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `attendancecorrection` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `attendanceDate` date NOT NULL,
  `originalLogin` datetime(3) DEFAULT NULL,
  `originalLogout` datetime(3) DEFAULT NULL,
  `requestedLogin` datetime(3) DEFAULT NULL,
  `requestedLogout` datetime(3) DEFAULT NULL,
  `reason` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('PENDING','APPROVED','REJECTED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `requestedById` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reviewedById` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reviewNote` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `appliedAt` datetime(3) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `AttendanceCorrection_locationId_status_idx` (`locationId`,`status`),
  KEY `AttendanceCorrection_employeeId_attendanceDate_idx` (`employeeId`,`attendanceDate`),
  KEY `AttendanceCorrection_status_createdAt_idx` (`status`,`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `notification` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `message` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` enum('INFO','WARNING','DANGER','CRITICAL') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'INFO',
  `entityType` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `entityId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isRead` tinyint(1) NOT NULL DEFAULT '0',
  `readAt` datetime(3) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `Notification_userId_isRead_createdAt_idx` (`userId`,`isRead`,`createdAt`),
  KEY `Notification_locationId_idx` (`locationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `device` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` enum('BIOMETRIC_PUNCH','QR_SCANNER','FACE_CAM') COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('ONLINE','OFFLINE','INACTIVE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ONLINE',
  `ipAddress` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastPingAt` datetime(3) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Device_code_key` (`code`),
  KEY `Device_locationId_idx` (`locationId`),
  KEY `Device_type_idx` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
