-- ===========================================================================
-- 003: USERS, EMPLOYEES & SHIFTS TABLES
-- Shifts, employees, user accounts (Prisma-canonical DDL)
-- ===========================================================================

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `shift` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `startTime` datetime(3) NOT NULL,
  `endTime` datetime(3) NOT NULL,
  `gracePeriod` int NOT NULL DEFAULT '5',
  `lateThreshold` int NOT NULL DEFAULT '5',
  `earlyLoginIncentive` tinyint(1) NOT NULL DEFAULT '1',
  `earlyLoginRatePerSecond` decimal(10,4) NOT NULL DEFAULT '1.0000',
  `maxDailyEarlyIncentive` decimal(15,2) DEFAULT NULL,
  `maxMonthlyEarlyIncentive` decimal(15,2) DEFAULT NULL,
  `latePenaltyEnabled` tinyint(1) NOT NULL DEFAULT '0',
  `latePenaltyRatePerSecond` decimal(10,4) NOT NULL DEFAULT '1.0000',
  `maxDailyLatePenalty` decimal(15,2) DEFAULT NULL,
  `maxMonthlyLatePenalty` decimal(15,2) DEFAULT NULL,
  `overtimeEnabled` tinyint(1) NOT NULL DEFAULT '1',
  `overtimeRatePerSecond` decimal(10,4) DEFAULT NULL,
  `earlyLogoutPenaltyEnabled` tinyint(1) NOT NULL DEFAULT '0',
  `earlyLogoutRatePerSecond` decimal(10,4) DEFAULT NULL,
  `lunchDurationMinutes` int NOT NULL DEFAULT '100',
  `teaDurationMinutes` int NOT NULL DEFAULT '20',
  `maleLunchMinutes` int NOT NULL DEFAULT '100',
  `femaleLunchMinutes` int NOT NULL DEFAULT '40',
  `maleTeaMinutes` int NOT NULL DEFAULT '20',
  `femaleTeaMinutes` int NOT NULL DEFAULT '15',
  `faceVerificationThreshold` decimal(5,2) NOT NULL DEFAULT '85.00',
  `qrDailyTokenEnabled` tinyint(1) NOT NULL DEFAULT '1',
  `qrOneTimeScan` tinyint(1) NOT NULL DEFAULT '1',
  `scannerRoles` json DEFAULT NULL,
  `status` enum('ACTIVE','INACTIVE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Shift_locationId_code_key` (`locationId`,`code`),
  KEY `Shift_locationId_idx` (`locationId`),
  KEY `Shift_status_idx` (`status`),
  KEY `Shift_departmentId_fkey` (`departmentId`),
  CONSTRAINT `Shift_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Shift_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `employee` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeCode` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `firstName` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lastName` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fullName` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gender` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dateOfBirth` datetime(3) DEFAULT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floorId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sectionId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shiftId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `designation` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role` enum('SUPER_ADMIN','ADMIN','HR_MANAGER','HR_EXECUTIVE','PAYROLL_MANAGER','LOCATION_MANAGER','FLOOR_MANAGER','DEPARTMENT_MANAGER','TEAM_LEAD','SALES_EMPLOYEE','TEA_BREAK_MANAGER','T_SHOP_OWNER','HR_AUDITOR','EMPLOYEE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'EMPLOYEE',
  `status` enum('ACTIVE','INACTIVE','ON_LEAVE','TERMINATED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  `joiningDate` datetime(3) NOT NULL,
  `exitDate` datetime(3) DEFAULT NULL,
  `faceProfileId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qrCodeId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dailyQRCodeId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Employee_employeeCode_key` (`employeeCode`),
  UNIQUE KEY `Employee_email_key` (`email`),
  KEY `Employee_employeeCode_idx` (`employeeCode`),
  KEY `Employee_locationId_idx` (`locationId`),
  KEY `Employee_floorId_idx` (`floorId`),
  KEY `Employee_departmentId_idx` (`departmentId`),
  KEY `Employee_sectionId_idx` (`sectionId`),
  KEY `Employee_status_idx` (`status`),
  KEY `Employee_shiftId_fkey` (`shiftId`),
  KEY `Employee_faceProfileId_fkey` (`faceProfileId`),
  KEY `Employee_qrCodeId_fkey` (`qrCodeId`),
  KEY `Employee_dailyQRCodeId_fkey` (`dailyQRCodeId`),
  CONSTRAINT `Employee_dailyQRCodeId_fkey` FOREIGN KEY (`dailyQRCodeId`) REFERENCES `qrcode` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Employee_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Employee_faceProfileId_fkey` FOREIGN KEY (`faceProfileId`) REFERENCES `faceprofile` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Employee_floorId_fkey` FOREIGN KEY (`floorId`) REFERENCES `floor` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Employee_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Employee_qrCodeId_fkey` FOREIGN KEY (`qrCodeId`) REFERENCES `qrcode` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Employee_sectionId_fkey` FOREIGN KEY (`sectionId`) REFERENCES `section` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Employee_shiftId_fkey` FOREIGN KEY (`shiftId`) REFERENCES `shift` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `user` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `passwordHash` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fullName` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` enum('SUPER_ADMIN','ADMIN','HR_MANAGER','HR_EXECUTIVE','PAYROLL_MANAGER','LOCATION_MANAGER','FLOOR_MANAGER','DEPARTMENT_MANAGER','TEAM_LEAD','SALES_EMPLOYEE','TEA_BREAK_MANAGER','T_SHOP_OWNER','HR_AUDITOR','EMPLOYEE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'EMPLOYEE',
  `permissions` json DEFAULT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT '1',
  `lastLoginAt` datetime(3) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `User_email_key` (`email`),
  KEY `User_email_idx` (`email`),
  KEY `User_role_idx` (`role`),
  KEY `User_locationId_idx` (`locationId`),
  KEY `User_employeeId_fkey` (`employeeId`),
  CONSTRAINT `User_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `User_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
