-- ===========================================================================
-- 004: ATTENDANCE & BREAK TRACKING (SUB-SECOND PUNCTUALITY)
-- Attendance, per-location attendance rules, breaks, weekly offs, holidays (Prisma-canonical DDL)
-- ===========================================================================

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `attendancerules` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `loginTime` datetime(3) NOT NULL,
  `logoutTime` datetime(3) NOT NULL,
  `gracePeriodMinutes` int NOT NULL DEFAULT '5',
  `lateThresholdMinutes` int NOT NULL DEFAULT '5',
  `earlyLoginIncentiveEnabled` tinyint(1) NOT NULL DEFAULT '1',
  `earlyLoginRatePerSecond` decimal(10,4) NOT NULL DEFAULT '1.0000',
  `earlyLoginMaxDaily` decimal(15,2) DEFAULT NULL,
  `earlyLoginMaxMonthly` decimal(15,2) DEFAULT NULL,
  `latePenaltyEnabled` tinyint(1) NOT NULL DEFAULT '0',
  `latePenaltyRatePerSecond` decimal(10,4) NOT NULL DEFAULT '1.0000',
  `latePenaltyMaxDaily` decimal(15,2) DEFAULT NULL,
  `latePenaltyMaxMonthly` decimal(15,2) DEFAULT NULL,
  `overtimeIncentiveEnabled` tinyint(1) NOT NULL DEFAULT '0',
  `overtimeRatePerSecond` decimal(10,4) DEFAULT NULL,
  `earlyLogoutPenaltyEnabled` tinyint(1) NOT NULL DEFAULT '0',
  `earlyLogoutRatePerSecond` decimal(10,4) DEFAULT NULL,
  `lunchDurationMinutes` int NOT NULL DEFAULT '100',
  `teaDurationMinutes` int NOT NULL DEFAULT '20',
  `maleLunchMinutes` int NOT NULL DEFAULT '100',
  `femaleLunchMinutes` int NOT NULL DEFAULT '40',
  `maleTeaMinutes` int NOT NULL DEFAULT '20',
  `femaleTeaMinutes` int NOT NULL DEFAULT '15',
  `faceVerificationThreshold` decimal(5,2) NOT NULL DEFAULT '85.00',
  `qrDailyTokenEnabled` tinyint(1) NOT NULL DEFAULT '1',
  `qrOneTimeScan` tinyint(1) NOT NULL DEFAULT '1',
  `scannerRoles` json DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `AttendanceRules_locationId_key` (`locationId`),
  KEY `AttendanceRules_locationId_idx` (`locationId`),
  CONSTRAINT `AttendanceRules_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `attendance` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `shiftId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `attendanceDate` date NOT NULL,
  `scheduledLogin` datetime(3) DEFAULT NULL,
  `actualLogin` datetime(3) DEFAULT NULL,
  `scheduledLogout` datetime(3) DEFAULT NULL,
  `actualLogout` datetime(3) DEFAULT NULL,
  `earlyLoginSeconds` int NOT NULL DEFAULT '0',
  `lateLoginSeconds` int NOT NULL DEFAULT '0',
  `earlyLogoutSeconds` int NOT NULL DEFAULT '0',
  `overtimeSeconds` int NOT NULL DEFAULT '0',
  `totalWorkingSeconds` int NOT NULL DEFAULT '0',
  `breakSeconds` int NOT NULL DEFAULT '0',
  `effectiveWorkingSeconds` int NOT NULL DEFAULT '0',
  `earlyLoginIncentive` decimal(15,2) NOT NULL DEFAULT '0.00',
  `lateLoginPenalty` decimal(15,2) NOT NULL DEFAULT '0.00',
  `overtimeIncentive` decimal(15,2) NOT NULL DEFAULT '0.00',
  `earlyLogoutPenalty` decimal(15,2) NOT NULL DEFAULT '0.00',
  `status` enum('PRESENT','ABSENT','LATE','EARLY','ON_LUNCH','ON_TEA_BREAK','ON_OTHER_BREAK','WEEKLY_OFF','OVERTIME','LEFT_STORE','FACE_VERIFIED','FACE_VERIFICATION_FAILED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ABSENT',
  `faceVerified` tinyint(1) NOT NULL DEFAULT '0',
  `faceMatchPercentage` decimal(5,2) DEFAULT NULL,
  `notes` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Attendance_employeeId_attendanceDate_key` (`employeeId`,`attendanceDate`),
  KEY `Attendance_locationId_attendanceDate_idx` (`locationId`,`attendanceDate`),
  KEY `Attendance_shiftId_idx` (`shiftId`),
  KEY `Attendance_status_idx` (`status`),
  CONSTRAINT `Attendance_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Attendance_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Attendance_shiftId_fkey` FOREIGN KEY (`shiftId`) REFERENCES `shift` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `breakrule` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `floorId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shiftId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employeeGroup` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `breakType` enum('LUNCH','TEA','OTHER') COLLATE utf8mb4_unicode_ci NOT NULL,
  `durationMinutes` int NOT NULL,
  `maxOccurrences` int NOT NULL DEFAULT '1',
  `isPaid` tinyint(1) NOT NULL DEFAULT '1',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `BreakRule_locationId_idx` (`locationId`),
  KEY `BreakRule_departmentId_idx` (`departmentId`),
  KEY `BreakRule_floorId_idx` (`floorId`),
  KEY `BreakRule_shiftId_idx` (`shiftId`),
  CONSTRAINT `BreakRule_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `BreakRule_floorId_fkey` FOREIGN KEY (`floorId`) REFERENCES `floor` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `BreakRule_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `BreakRule_shiftId_fkey` FOREIGN KEY (`shiftId`) REFERENCES `shift` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `employeebreak` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `breakType` enum('LUNCH','TEA','OTHER') COLLATE utf8mb4_unicode_ci NOT NULL,
  `breakDate` date NOT NULL,
  `startTime` datetime(3) DEFAULT NULL,
  `endTime` datetime(3) DEFAULT NULL,
  `allowedDuration` int NOT NULL,
  `actualDuration` int DEFAULT NULL,
  `excessDuration` int DEFAULT NULL,
  `status` enum('NOT_STARTED','ACTIVE','COMPLETED','EXCEEDED','MANUALLY_ADJUSTED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NOT_STARTED',
  `qrScanId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `EmployeeBreak_employeeId_breakDate_idx` (`employeeId`,`breakDate`),
  KEY `EmployeeBreak_breakType_idx` (`breakType`),
  KEY `EmployeeBreak_status_idx` (`status`),
  KEY `EmployeeBreak_qrScanId_fkey` (`qrScanId`),
  CONSTRAINT `EmployeeBreak_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `EmployeeBreak_qrScanId_fkey` FOREIGN KEY (`qrScanId`) REFERENCES `qrscanrecord` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `weeklyoffrule` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `floorId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employeeId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shiftId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dayOfWeek` enum('SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','ROTATIONAL') COLLATE utf8mb4_unicode_ci NOT NULL,
  `isRotational` tinyint(1) NOT NULL DEFAULT '0',
  `rotationPattern` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `effectiveFrom` date NOT NULL,
  `effectiveTo` date DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `WeeklyOffRule_locationId_idx` (`locationId`),
  KEY `WeeklyOffRule_employeeId_idx` (`employeeId`),
  KEY `WeeklyOffRule_floorId_idx` (`floorId`),
  KEY `WeeklyOffRule_departmentId_idx` (`departmentId`),
  KEY `WeeklyOffRule_shiftId_idx` (`shiftId`),
  CONSTRAINT `WeeklyOffRule_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `WeeklyOffRule_employeeId_fkey` FOREIGN KEY (`employeeId`) REFERENCES `employee` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `WeeklyOffRule_floorId_fkey` FOREIGN KEY (`floorId`) REFERENCES `floor` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `WeeklyOffRule_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `WeeklyOffRule_shiftId_fkey` FOREIGN KEY (`shiftId`) REFERENCES `shift` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `holiday` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `date` date NOT NULL,
  `locationId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `departmentId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isRecurring` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `Holiday_date_idx` (`date`),
  KEY `Holiday_locationId_idx` (`locationId`),
  KEY `Holiday_departmentId_fkey` (`departmentId`),
  CONSTRAINT `Holiday_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Holiday_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `location` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
