import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export async function GET(request: Request) {
  const terminals = [
    {
      id: 'TERM-01',
      code: 'BEL-01',
      name: 'BEL-01 Entrance Face Gate A',
      location: 'Belagavi Flagship (Karnataka HQ)',
      ipAddress: '192.168.10.21',
      status: 'ONLINE',
      latency: 12, // <50ms green
      packetLoss: 0.0,
      heartbeat: '2s ago',
      uptime: 99.9,
      firmwareVersion: 'v3.2.1-prod',
      updateAvailable: false,
      punchesRecordedToday: 28,
      cameraActive: true,
      mode: 'ACTIVE_SCAN',
    },
    {
      id: 'TERM-02',
      code: 'BEL-02',
      name: 'BEL-02 Floor 1 Loom Terminal B',
      location: 'Belagavi Flagship (Weaving Bay)',
      ipAddress: '192.168.10.22',
      status: 'ONLINE',
      latency: 18,
      packetLoss: 0.0,
      heartbeat: '4s ago',
      uptime: 99.8,
      firmwareVersion: 'v3.2.1-prod',
      updateAvailable: false,
      punchesRecordedToday: 14,
      cameraActive: true,
      mode: 'ACTIVE_SCAN',
    },
    {
      id: 'TERM-03',
      code: 'BEL-03',
      name: 'BEL-03 Tea & Canteen Scanner C',
      location: 'Belagavi Flagship (Refreshment Hub)',
      ipAddress: '192.168.10.23',
      status: 'ONLINE',
      latency: 15,
      packetLoss: 0.0,
      heartbeat: '1s ago',
      uptime: 100.0,
      firmwareVersion: 'v3.2.1-prod',
      updateAvailable: false,
      punchesRecordedToday: 42,
      cameraActive: true,
      mode: 'ACTIVE_SCAN',
    },
    {
      id: 'TERM-04',
      code: 'BEL-04',
      name: 'BEL-04 Dispatch Gate Terminal D',
      location: 'Belagavi Flagship (Loading Bay)',
      ipAddress: '192.168.10.24',
      status: 'ONLINE',
      latency: 22,
      packetLoss: 0.0,
      heartbeat: '6s ago',
      uptime: 99.7,
      firmwareVersion: 'v3.1.9-stable',
      updateAvailable: true, // Update Available badge!
      punchesRecordedToday: 9,
      cameraActive: true,
      mode: 'ACTIVE_SCAN',
    },
    {
      id: 'TERM-05',
      code: 'DAV-02A',
      name: 'DAV-02 Main Showroom Scanner 1',
      location: 'Davanagere Showroom (KB Extension)',
      ipAddress: '192.168.20.15',
      status: 'ONLINE',
      latency: 19,
      packetLoss: 0.0,
      heartbeat: '3s ago',
      uptime: 99.8,
      firmwareVersion: 'v3.2.1-prod',
      updateAvailable: false,
      punchesRecordedToday: 18,
      cameraActive: true,
      mode: 'ACTIVE_SCAN',
    },
    {
      id: 'TERM-06',
      code: 'DAV-02B',
      name: 'DAV-02 Staff Lounge Biometric 2',
      location: 'Davanagere Showroom (Fitting Wing)',
      ipAddress: '192.168.20.16',
      status: 'ONLINE',
      latency: 24,
      packetLoss: 0.0,
      heartbeat: '8s ago',
      uptime: 99.6,
      firmwareVersion: 'v3.2.1-prod',
      updateAvailable: false,
      punchesRecordedToday: 11,
      cameraActive: true,
      mode: 'ACTIVE_SCAN',
    },
    {
      id: 'TERM-07',
      code: 'SHI-03A',
      name: 'SHI-03 Front Concierge Face Cam 1',
      location: 'Shivamogga Retail Apex (B.H. Road)',
      ipAddress: '192.168.30.10',
      status: 'ONLINE',
      latency: 16,
      packetLoss: 0.0,
      heartbeat: '2s ago',
      uptime: 100.0,
      firmwareVersion: 'v3.2.1-prod',
      updateAvailable: false,
      punchesRecordedToday: 21,
      cameraActive: true,
      mode: 'ACTIVE_SCAN',
    },
    {
      id: 'TERM-08',
      code: 'SHI-03B',
      name: 'SHI-03 Weaving Stock Entry Cam 2',
      location: 'Shivamogga Retail Apex (Inventory Base)',
      ipAddress: '192.168.30.11',
      status: 'ONLINE',
      latency: 20,
      packetLoss: 0.0,
      heartbeat: '5s ago',
      uptime: 99.9,
      firmwareVersion: 'v3.2.0-prod',
      updateAvailable: false,
      punchesRecordedToday: 15,
      cameraActive: true,
      mode: 'ACTIVE_SCAN',
    },
  ];

  // Network packet loss & latency metrics
  const networkMetrics = {
    totalTerminals: 8,
    onlineTerminals: 8,
    offlineTerminals: 0,
    maintenanceTerminals: 0,
    averageLatencyMs: 18,
    averagePacketLossPct: 0.0,
    packetLossGraph: [
      { time: '08:00', lossPct: 0.0, latency: 17 },
      { time: '08:30', lossPct: 0.0, latency: 19 },
      { time: '09:00', lossPct: 0.0, latency: 21 },
      { time: '09:30', lossPct: 0.0, latency: 18 },
      { time: '10:00', lossPct: 0.0, latency: 16 },
      { time: 'Current', lossPct: 0.0, latency: 18 },
    ],
    latencyDistribution: [
      { bucket: '< 15ms (Ultra-Fast)', count: 2, color: '#10b981' },
      { bucket: '15 - 20ms (Optimal)', count: 4, color: '#0058be' },
      { bucket: '21 - 30ms (Good)', count: 2, color: '#3b82f6' },
      { bucket: '31 - 50ms (Fair)', count: 0, color: '#f59e0b' },
      { bucket: '> 50ms (Degraded)', count: 0, color: '#ef4444' },
    ],
    hubsSummary: [
      { hub: 'Belagavi Flagship (BEL)', terminals: 4, status: 'All Online' },
      { hub: 'Davanagere Showroom (DAV)', terminals: 2, status: 'All Online' },
      { hub: 'Shivamogga Apex (SHI)', terminals: 2, status: 'All Online' },
    ]
  };

  return NextResponse.json({
    success: true,
    data: {
      terminals,
      networkMetrics,
    },
    timestamp: new Date().toISOString(),
  });
}
