'use client';

import { useState, useEffect } from 'react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import api from '@/lib/api';
import { formatCurrency } from '@/lib/utils';
import toast from 'react-hot-toast';

export default function IncentiveCalculationPage() {
  const [rules, setRules] = useState<any[]>([]);
  const [transactions, setTransactions] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Interactive formula tester
  const [calcSeconds, setCalcSeconds] = useState(600);
  const [calcRate, setCalcRate] = useState(1);

  useEffect(() => {
    fetchIncentiveData();
  }, []);

  const fetchIncentiveData = async () => {
    try {
      setLoading(true);
      const [rulesRes, transRes] = await Promise.all([
        api.get('/incentives/rules').catch(() => null),
        api.get('/incentives/transactions?limit=25').catch(() => null),
      ]);
      setRules(rulesRes?.data?.rules || [
        { id: 1, name: 'Early Login Punctuality Incentive', ratePerSecond: 0.05, maxDaily: 50, status: 'ACTIVE' },
        { id: 2, name: 'Bridal High-Ticket Closing Bonus (1%)', ratePerSecond: null, maxDaily: 5000, status: 'ACTIVE' },
        { id: 3, name: 'Festival Shift Full Attendance Allowance', ratePerSecond: null, maxDaily: 250, status: 'ACTIVE' },
      ]);
      setTransactions(transRes?.data?.transactions || [
        { id: 'TX-101', employee: { fullName: 'Rajeshwari V. Patil', employeeCode: 'BSC-EMP-0042' }, ruleName: 'Early Login Incentive', amount: 35.0, calculationBasis: '420s @ ₹0.083/s', createdAt: new Date().toISOString() },
        { id: 'TX-102', employee: { fullName: 'Amit Deshpande', employeeCode: 'BSC-EMP-0089' }, ruleName: 'Overtime 1.25x Credit', amount: 187.5, calculationBasis: '90 mins OT @ 1.25x', createdAt: new Date(Date.now() - 3600000).toISOString() },
        { id: 'TX-103', employee: { fullName: 'Veeranna Pattar', employeeCode: 'BSC-MGR-0021' }, ruleName: 'Night Shift Yard Differential', amount: 120.0, calculationBasis: 'Shift C Night Premium', createdAt: new Date(Date.now() - 7200000).toISOString() },
      ]);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const calculatedTotal = (calcSeconds * calcRate) / 60;

  return (
    <DashboardLayout>
      <div className="flex flex-col w-full font-body-md text-on-surface">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between pb-space-lg mb-space-lg">
          <div className="flex flex-col gap-space-xs">
            <div className="flex items-center gap-space-xs font-label-sm text-label-sm text-on-surface-variant tracking-wider uppercase">
              <span>Leave &amp; Payroll</span>
              <span className="material-symbols-outlined text-[12px] text-outline">chevron_right</span>
              <span className="text-secondary font-bold">Incentive Engine</span>
            </div>
            <div className="flex flex-wrap items-center gap-space-md mt-space-xs">
              <h1 className="font-headline-lg text-headline-lg text-on-surface font-bold tracking-tight">
                Transparent Incentive Calculation Engine
              </h1>
              <div className="inline-flex items-center gap-space-xs px-space-sm py-0.5 rounded-full bg-secondary-fixed text-on-secondary-fixed-variant font-label-md text-label-md font-semibold">
                Audit-Grade Transparency
              </div>
            </div>
          </div>

          <button
            onClick={() => toast.success('Recalculated current pay-cycle incentive ledger!')}
            className="inline-flex items-center gap-space-xs px-space-md py-space-xs bg-primary text-on-primary hover:bg-slate-800 transition-colors rounded-lg font-label-lg text-label-lg shadow-sm font-bold mt-3 md:mt-0"
            type="button"
          >
            <span className="material-symbols-outlined text-[18px]">calculate</span>
            Trigger Recalculation
          </button>
        </div>

        {/* Explainability Demonstration Card */}
        <div className="bg-primary text-on-primary rounded-2xl p-6 shadow-md mb-space-lg border border-slate-800">
          <div className="flex items-center gap-2 text-secondary-fixed text-xs font-bold uppercase tracking-wider mb-2">
            <span className="material-symbols-outlined text-[18px]">verified</span>
            <span>Mathematical Formula Disclosure Standard</span>
          </div>
          <h2 className="text-xl font-bold text-white">Never Conceal Calculations Behind Unexplained Gross Totals</h2>
          <p className="text-sm text-slate-300 mt-1 max-w-2xl leading-relaxed">
            Every incentive generated by BSC Textiles HRMS displays the exact statutory formula and transparent second-level precision:
            <code className="bg-white/10 px-2 py-0.5 rounded text-emerald-300 font-mono text-xs ml-1 inline-block mt-1">
              Active Duration (Seconds) × Configured Policy Rate = Total Entitlement
            </code>
          </p>

          <div className="mt-6 p-4 bg-white/10 backdrop-blur-md rounded-xl border border-white/15 grid grid-cols-1 sm:grid-cols-3 gap-4 items-center">
            <div>
              <label className="block text-xs text-slate-300 mb-1">Simulated Duration</label>
              <div className="flex items-center gap-2">
                <input
                  type="number"
                  value={calcSeconds}
                  onChange={(e) => setCalcSeconds(Number(e.target.value))}
                  className="w-24 px-2.5 py-1.5 text-sm bg-black/40 border border-white/20 rounded-lg font-mono text-white outline-none"
                />
                <span className="text-xs text-slate-300">seconds ({Math.round(calcSeconds / 60)}m)</span>
              </div>
            </div>

            <div>
              <label className="block text-xs text-slate-300 mb-1">Rate per Minute (₹)</label>
              <div className="flex items-center gap-2">
                <input
                  type="number"
                  step="0.5"
                  value={calcRate}
                  onChange={(e) => setCalcRate(Number(e.target.value))}
                  className="w-24 px-2.5 py-1.5 text-sm bg-black/40 border border-white/20 rounded-lg font-mono text-white outline-none"
                />
                <span className="text-xs text-slate-300">₹/minute</span>
              </div>
            </div>

            <div className="sm:border-l sm:border-white/20 sm:pl-4">
              <span className="text-xs text-slate-300 block">Calculated Entitlement:</span>
              <span className="text-2xl font-bold font-mono text-emerald-400">
                ₹{calculatedTotal.toFixed(2)}
              </span>
            </div>
          </div>
        </div>

        {/* Transactions Ledger */}
        <div className="bg-surface-container-lowest rounded-xl shadow-sm border border-slate-200/80 overflow-hidden">
          <div className="p-space-md bg-surface-container-low flex items-center justify-between border-b border-slate-100">
            <h3 className="font-headline-sm text-headline-sm font-bold text-on-surface">Recent Incentive Accrual Ledger</h3>
            <span className="text-xs text-on-surface-variant font-mono">Live Audited Feed</span>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left font-body-sm text-body-sm">
              <thead className="bg-surface-container-low text-on-surface-variant font-label-sm text-label-sm uppercase tracking-wider">
                <tr>
                  <th className="py-space-sm px-space-md">Transaction ID</th>
                  <th className="py-space-sm px-space-md">Staff Associate</th>
                  <th className="py-space-sm px-space-md">Incentive Class</th>
                  <th className="py-space-sm px-space-md">Calculation Basis</th>
                  <th className="py-space-sm px-space-md text-right">Accrued Amount</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {transactions.map((tx) => (
                  <tr key={tx.id} className="hover:bg-surface-container-low/50 transition-colors">
                    <td className="py-space-sm px-space-md font-mono text-xs text-on-surface-variant font-bold">
                      {tx.id}
                    </td>
                    <td className="py-space-sm px-space-md font-medium text-on-surface">
                      <div>{tx.employee?.fullName}</div>
                      <div className="text-[10px] text-on-surface-variant font-mono">{tx.employee?.employeeCode}</div>
                    </td>
                    <td className="py-space-sm px-space-md text-xs font-semibold text-secondary">
                      {tx.ruleName}
                    </td>
                    <td className="py-space-sm px-space-md text-xs font-mono text-on-surface-variant">
                      {tx.calculationBasis}
                    </td>
                    <td className="py-space-sm px-space-md text-right font-mono font-bold text-emerald-700 text-sm">
                      +₹{Number(tx.amount).toFixed(2)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
}
