'use client';

import { useState, useEffect } from 'react';
import { 
  DollarSign, Calculator, TrendingUp, Shield, 
  HelpCircle, CheckCircle, RefreshCw, Eye 
} from 'lucide-react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import api from '@/lib/api';
import { formatCurrency } from '@/lib/utils';

export default function IncentiveCalculationPage() {
  const [rules, setRules] = useState<any[]>([]);
  const [transactions, setTransactions] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Interactive formula tester
  const [calcSeconds, setCalcSeconds] = useState(600);
  const [calcRate, setCalcRate] = useState(1);

  useEffect(() => {
    fetchIncentiveData();
  }, []);

  const fetchIncentiveData = async () => {
    try {
      setLoading(true);
      const [rulesRes, transRes] = await Promise.all([
        api.get('/incentives/rules'),
        api.get('/incentives/transactions?limit=25').catch(() => ({ data: { transactions: [] } })),
      ]);
      setRules(rulesRes.data?.rules || []);
      setTransactions(transRes.data?.transactions || []);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Incentive Calculation Engine</h1>
          <p className="text-sm text-gray-500 mt-1">
            Explainable second-level incentives, sales performance bonuses, and transparent audit calculations
          </p>
        </div>

        {/* Explainability Demonstration Card */}
        <div className="bg-gradient-to-br from-emerald-900 via-primary-900 to-indigo-950 rounded-2xl p-6 text-white shadow-lg">
          <div className="flex items-center gap-2 text-emerald-300 text-xs font-bold uppercase tracking-wider mb-2">
            <Calculator className="w-4 h-4" />
            <span>Calculation Transparency Standard</span>
          </div>
          <h2 className="text-xl font-bold">Never Hide Calculations Behind Unexplained Totals</h2>
          <p className="text-sm text-primary-100 mt-1 max-w-2xl">
            Every incentive generated by the BSC Textiles HRMS displays the exact formula:
            <code className="bg-white/10 px-2 py-0.5 rounded text-emerald-300 font-mono text-xs ml-1">
              Duration (Seconds) × Configured Rate = Total Incentive
            </code>
          </p>

          <div className="mt-6 p-4 bg-white/10 backdrop-blur-md rounded-xl border border-white/20 grid grid-cols-1 sm:grid-cols-3 gap-4 items-center">
            <div>
              <label className="block text-xs text-primary-200 mb-1">Early Duration</label>
              <div className="flex items-center gap-2">
                <input
                  type="number"
                  value={calcSeconds}
                  onChange={(e) => setCalcSeconds(Number(e.target.value))}
                  className="w-24 px-2 py-1 text-sm bg-white/20 border border-white/30 rounded font-mono text-white outline-none"
                />
                <span className="text-xs text-primary-200">seconds ({Math.round(calcSeconds / 60)} mins)</span>
              </div>
            </div>

            <div>
              <label className="block text-xs text-primary-200 mb-1">Configured Rate</label>
              <div className="flex items-center gap-2">
                <span className="font-bold text-emerald-300">₹</span>
                <input
                  type="number"
                  step="0.1"
                  value={calcRate}
                  onChange={(e) => setCalcRate(Number(e.target.value))}
                  className="w-20 px-2 py-1 text-sm bg-white/20 border border-white/30 rounded font-mono text-white outline-none"
                />
                <span className="text-xs text-primary-200">/ second</span>
              </div>
            </div>

            <div className="sm:text-right border-t sm:border-t-0 sm:border-l border-white/20 pt-3 sm:pt-0 sm:pl-4">
              <span className="block text-xs uppercase text-emerald-300 font-semibold">Calculated Payout</span>
              <span className="text-2xl font-mono font-bold text-white">
                {formatCurrency(calcSeconds * calcRate)}
              </span>
            </div>
          </div>
        </div>

        {/* Active Incentive Rules */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
          <div className="p-5 border-b border-gray-200">
            <h3 className="font-bold text-gray-900">Active Configured Incentive Rules</h3>
            <p className="text-xs text-gray-500 mt-0.5">Rules applying to retail branches, sales floors, and selling points</p>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm text-gray-600">
              <thead className="bg-gray-50 text-xs uppercase font-semibold text-gray-700 border-b border-gray-200">
                <tr>
                  <th className="py-3 px-4">Rule Name</th>
                  <th className="py-3 px-4">Type</th>
                  <th className="py-3 px-4">Calculation Method</th>
                  <th className="py-3 px-4">Configured Rate / Amount</th>
                  <th className="py-3 px-4">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {rules.map((r) => (
                  <tr key={r.id} className="hover:bg-gray-50/80 transition-colors">
                    <td className="py-3 px-4 font-semibold text-gray-900">{r.name}</td>
                    <td className="py-3 px-4 text-xs font-mono">{r.incentiveType}</td>
                    <td className="py-3 px-4 text-xs">{r.calculationType?.replace(/_/g, ' ')}</td>
                    <td className="py-3 px-4 font-mono font-bold text-emerald-700 text-xs">
                      {r.amount ? `₹${r.amount}${r.calculationType === 'PER_SECOND' ? ' / sec' : ''}` : `${r.percentage}% Target`}
                    </td>
                    <td className="py-3 px-4">
                      <span className="px-2 py-0.5 text-xs font-semibold rounded-full bg-emerald-100 text-emerald-800">
                        {r.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
}
